vich_uploader:
    db_driver: orm

    mappings:
       images:
           uri_prefix: /uploads/images
           upload_destination: '%kernel.project_dir%/public/uploads/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       user_profiles:
           uri_prefix: /uploads/profiles
           upload_destination: '%kernel.project_dir%/public/uploads/profiles'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

       weapon_images:
           uri_prefix: /uploads/weapons
           upload_destination: '%kernel.project_dir%/public/uploads/weapons'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
